import 'package:flutter_web/painting.dart';

var style = {
  'container': TextStyle(backgroundColor: Color(0xff282b2e)),
  'keyword': TextStyle(color: Color(0xff93c763)),
  'selector-tag': TextStyle(color: Color(0xff93c763)),
  'literal': TextStyle(color: Color(0xff93c763)),
  'selector-id': TextStyle(color: Color(0xff93c763)),
  'number': TextStyle(color: Color(0xffffcd22)),
  'container': TextStyle(color: Color(0xffe0e2e4)),
  'attribute': TextStyle(color: Color(0xff668bb0)),
  'regexp': TextStyle(color: Color(0xffd39745)),
  'link': TextStyle(color: Color(0xffd39745)),
  'meta': TextStyle(color: Color(0xff557182)),
  'tag': TextStyle(color: Color(0xff8cbbad)),
  'name': TextStyle(color: Color(0xff8cbbad)),
  'bullet': TextStyle(color: Color(0xff8cbbad)),
  'subst': TextStyle(color: Color(0xff8cbbad)),
  'emphasis': TextStyle(color: Color(0xff8cbbad)),
  'type': TextStyle(color: Color(0xff8cbbad)),
  'built_in': TextStyle(color: Color(0xff8cbbad)),
  'selector-attr': TextStyle(color: Color(0xff8cbbad)),
  'selector-pseudo': TextStyle(color: Color(0xff8cbbad)),
  'addition': TextStyle(color: Color(0xff8cbbad)),
  'variable': TextStyle(color: Color(0xff8cbbad)),
  'template-tag': TextStyle(color: Color(0xff8cbbad)),
  'template-variable': TextStyle(color: Color(0xff8cbbad)),
  'string': TextStyle(color: Color(0xffec7600)),
  'symbol': TextStyle(color: Color(0xffec7600)),
  'comment': TextStyle(color: Color(0xff818e96)),
  'quote': TextStyle(color: Color(0xff818e96)),
  'deletion': TextStyle(color: Color(0xff818e96)),
  'selector-class': TextStyle(color: Color(0xffA082BD)),
  'keyword': TextStyle(fontWeight: FontWeight.bold),
  'selector-tag': TextStyle(fontWeight: FontWeight.bold),
  'literal': TextStyle(fontWeight: FontWeight.bold),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'title': TextStyle(fontWeight: FontWeight.bold),
  'section': TextStyle(fontWeight: FontWeight.bold),
  'type': TextStyle(fontWeight: FontWeight.bold),
  'name': TextStyle(fontWeight: FontWeight.bold),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
