import 'package:flutter_web/painting.dart';

var style = {
  'keyword': TextStyle(color: Color(0xff005599), fontWeight: FontWeight.bold),
  'selector-tag':
      TextStyle(color: Color(0xff005599), fontWeight: FontWeight.bold),
  'literal': TextStyle(color: Color(0xff005599), fontWeight: FontWeight.bold),
  'container': TextStyle(color: Color(0xff3e5915)),
  'subst': TextStyle(color: Color(0xff3e5915)),
  'string': TextStyle(color: Color(0xff2c009f)),
  'title': TextStyle(color: Color(0xff2c009f), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xff2c009f), fontWeight: FontWeight.bold),
  'type': TextStyle(color: Color(0xff2c009f), fontWeight: FontWeight.bold),
  'symbol': TextStyle(color: Color(0xff2c009f)),
  'bullet': TextStyle(color: Color(0xff2c009f)),
  'attribute': TextStyle(color: Color(0xff2c009f)),
  'built_in': TextStyle(color: Color(0xff2c009f)),
  'builtin-name': TextStyle(color: Color(0xff2c009f)),
  'addition': TextStyle(color: Color(0xff2c009f)),
  'variable': TextStyle(color: Color(0xff2c009f)),
  'template-tag': TextStyle(color: Color(0xff2c009f)),
  'template-variable': TextStyle(color: Color(0xff2c009f)),
  'link': TextStyle(color: Color(0xff2c009f)),
  'comment': TextStyle(color: Color(0xffe60415)),
  'quote': TextStyle(color: Color(0xffe60415)),
  'deletion': TextStyle(color: Color(0xffe60415)),
  'meta': TextStyle(color: Color(0xffe60415)),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'name': TextStyle(fontWeight: FontWeight.bold),
  'selector-id': TextStyle(fontWeight: FontWeight.bold),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
};
