// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const arduinoLightTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xffFFFFFF), color: Color(0xff434f54)),
  'subst': TextStyle(color: Color(0xff434f54)),
  'keyword': TextStyle(color: Color(0xff00979D)),
  'attribute': TextStyle(color: Color(0xff00979D)),
  'selector-tag': TextStyle(color: Color(0xff00979D)),
  'doctag': TextStyle(color: Color(0xff00979D)),
  'name': TextStyle(color: Color(0xff00979D)),
  'built_in': TextStyle(color: Color(0xffD35400)),
  'literal': TextStyle(color: Color(0xffD35400)),
  'bullet': TextStyle(color: Color(0xffD35400)),
  'code': TextStyle(color: Color(0xffD35400)),
  'addition': TextStyle(color: Color(0xffD35400)),
  'regexp': TextStyle(color: Color(0xff00979D)),
  'symbol': TextStyle(color: Color(0xff00979D)),
  'variable': TextStyle(color: Color(0xff00979D)),
  'template-variable': TextStyle(color: Color(0xff00979D)),
  'link': TextStyle(color: Color(0xff00979D)),
  'selector-attr': TextStyle(color: Color(0xff00979D)),
  'selector-pseudo': TextStyle(color: Color(0xff00979D)),
  'type': TextStyle(color: Color(0xff005C5F)),
  'string': TextStyle(color: Color(0xff005C5F)),
  'selector-id': TextStyle(color: Color(0xff005C5F)),
  'selector-class': TextStyle(color: Color(0xff005C5F)),
  'quote': TextStyle(color: Color(0xff005C5F)),
  'template-tag': TextStyle(color: Color(0xff005C5F)),
  'deletion': TextStyle(color: Color(0xff005C5F)),
  'title': TextStyle(color: Color(0xff880000), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xff880000), fontWeight: FontWeight.bold),
  'comment': TextStyle(color: Color.fromRGBO(149, 165, 166, .8)),
  'meta-keyword': TextStyle(color: Color(0xff728E00)),
  'meta': TextStyle(color: Color(0xff434f54)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'function': TextStyle(color: Color(0xff728E00)),
  'number': TextStyle(color: Color(0xff8A7B52)),
};
