// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const defaultTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xffF0F0F0), color: Color(0xff444444)),
  'subst': TextStyle(color: Color(0xff444444)),
  'comment': TextStyle(color: Color(0xff888888)),
  'keyword': TextStyle(fontWeight: FontWeight.bold),
  'attribute': TextStyle(fontWeight: FontWeight.bold),
  'selector-tag': TextStyle(fontWeight: FontWeight.bold),
  'meta-keyword': TextStyle(fontWeight: FontWeight.bold),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'name': TextStyle(fontWeight: FontWeight.bold),
  'type': TextStyle(color: Color(0xff880000)),
  'string': TextStyle(color: Color(0xff880000)),
  'number': TextStyle(color: Color(0xff880000)),
  'selector-id': TextStyle(color: Color(0xff880000)),
  'selector-class': TextStyle(color: Color(0xff880000)),
  'quote': TextStyle(color: Color(0xff880000)),
  'template-tag': TextStyle(color: Color(0xff880000)),
  'deletion': TextStyle(color: Color(0xff880000)),
  'title': TextStyle(color: Color(0xff880000), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xff880000), fontWeight: FontWeight.bold),
  'regexp': TextStyle(color: Color(0xffBC6060)),
  'symbol': TextStyle(color: Color(0xffBC6060)),
  'variable': TextStyle(color: Color(0xffBC6060)),
  'template-variable': TextStyle(color: Color(0xffBC6060)),
  'link': TextStyle(color: Color(0xffBC6060)),
  'selector-attr': TextStyle(color: Color(0xffBC6060)),
  'selector-pseudo': TextStyle(color: Color(0xffBC6060)),
  'literal': TextStyle(color: Color(0xff78A960)),
  'built_in': TextStyle(color: Color(0xff397300)),
  'bullet': TextStyle(color: Color(0xff397300)),
  'code': TextStyle(color: Color(0xff397300)),
  'addition': TextStyle(color: Color(0xff397300)),
  'meta': TextStyle(color: Color(0xff1f7199)),
  'meta-string': TextStyle(color: Color(0xff4d99bf)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
