// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const gmlTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff222222), color: Color(0xffC0C0C0)),
  'keyword': TextStyle(color: Color(0xffFFB871), fontWeight: FontWeight.bold),
  'built_in': TextStyle(color: Color(0xffFFB871)),
  'literal': TextStyle(color: Color(0xffFF8080)),
  'symbol': TextStyle(color: Color(0xff58E55A)),
  'comment': TextStyle(color: Color(0xff5B995B)),
  'string': TextStyle(color: Color(0xffFFFF00)),
  'number': TextStyle(color: Color(0xffFF8080)),
  'attribute': TextStyle(color: Color(0xffC0C0C0)),
  'selector-tag': TextStyle(color: Color(0xffC0C0C0)),
  'doctag': TextStyle(color: Color(0xffC0C0C0)),
  'name': TextStyle(color: Color(0xffC0C0C0)),
  'bullet': TextStyle(color: Color(0xffC0C0C0)),
  'code': TextStyle(color: Color(0xffC0C0C0)),
  'addition': TextStyle(color: Color(0xffC0C0C0)),
  'regexp': TextStyle(color: Color(0xffC0C0C0)),
  'variable': TextStyle(color: Color(0xffC0C0C0)),
  'template-variable': TextStyle(color: Color(0xffC0C0C0)),
  'link': TextStyle(color: Color(0xffC0C0C0)),
  'selector-attr': TextStyle(color: Color(0xffC0C0C0)),
  'selector-pseudo': TextStyle(color: Color(0xffC0C0C0)),
  'type': TextStyle(color: Color(0xffC0C0C0)),
  'selector-id': TextStyle(color: Color(0xffC0C0C0)),
  'selector-class': TextStyle(color: Color(0xffC0C0C0)),
  'quote': TextStyle(color: Color(0xffC0C0C0)),
  'template-tag': TextStyle(color: Color(0xffC0C0C0)),
  'deletion': TextStyle(color: Color(0xffC0C0C0)),
  'title': TextStyle(color: Color(0xffC0C0C0)),
  'section': TextStyle(color: Color(0xffC0C0C0)),
  'function': TextStyle(color: Color(0xffC0C0C0)),
  'meta-keyword': TextStyle(color: Color(0xffC0C0C0)),
  'meta': TextStyle(color: Color(0xffC0C0C0)),
  'subst': TextStyle(color: Color(0xffC0C0C0)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
