// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const gruvboxDarkTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff282828), color: Color(0xffebdbb2)),
  'subst': TextStyle(color: Color(0xffebdbb2)),
  'deletion': TextStyle(color: Color(0xfffb4934)),
  'formula': TextStyle(color: Color(0xfffb4934)),
  'keyword': TextStyle(color: Color(0xfffb4934)),
  'link': TextStyle(color: Color(0xfffb4934)),
  'selector-tag': TextStyle(color: Color(0xfffb4934)),
  'built_in': TextStyle(color: Color(0xff83a598)),
  'emphasis': TextStyle(color: Color(0xff83a598), fontStyle: FontStyle.italic),
  'name': TextStyle(color: Color(0xff83a598)),
  'quote': TextStyle(color: Color(0xff83a598)),
  'strong': TextStyle(color: Color(0xff83a598), fontWeight: FontWeight.bold),
  'title': TextStyle(color: Color(0xff83a598)),
  'variable': TextStyle(color: Color(0xff83a598)),
  'attr': TextStyle(color: Color(0xfffabd2f)),
  'params': TextStyle(color: Color(0xfffabd2f)),
  'template-tag': TextStyle(color: Color(0xfffabd2f)),
  'type': TextStyle(color: Color(0xfffabd2f)),
  'builtin-name': TextStyle(color: Color(0xff8f3f71)),
  'doctag': TextStyle(color: Color(0xff8f3f71)),
  'literal': TextStyle(color: Color(0xffd3869b)),
  'number': TextStyle(color: Color(0xffd3869b)),
  'code': TextStyle(color: Color(0xfffe8019)),
  'meta': TextStyle(color: Color(0xfffe8019)),
  'regexp': TextStyle(color: Color(0xfffe8019)),
  'selector-id': TextStyle(color: Color(0xfffe8019)),
  'template-variable': TextStyle(color: Color(0xfffe8019)),
  'addition': TextStyle(color: Color(0xffb8bb26)),
  'meta-string': TextStyle(color: Color(0xffb8bb26)),
  'section': TextStyle(color: Color(0xffb8bb26), fontWeight: FontWeight.bold),
  'selector-attr': TextStyle(color: Color(0xffb8bb26)),
  'selector-class': TextStyle(color: Color(0xffb8bb26)),
  'string': TextStyle(color: Color(0xffb8bb26)),
  'symbol': TextStyle(color: Color(0xffb8bb26)),
  'attribute': TextStyle(color: Color(0xff8ec07c)),
  'bullet': TextStyle(color: Color(0xff8ec07c)),
  'class': TextStyle(color: Color(0xff8ec07c)),
  'function': TextStyle(color: Color(0xff8ec07c)),
  'meta-keyword': TextStyle(color: Color(0xff8ec07c)),
  'selector-pseudo': TextStyle(color: Color(0xff8ec07c)),
  'tag': TextStyle(color: Color(0xff8ec07c), fontWeight: FontWeight.bold),
  'comment': TextStyle(color: Color(0xff928374), fontStyle: FontStyle.italic),
  'link_label': TextStyle(color: Color(0xffd3869b)),
};
