// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const solarizedLightTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xfffdf6e3), color: Color(0xff657b83)),
  'comment': TextStyle(color: Color(0xff93a1a1)),
  'quote': TextStyle(color: Color(0xff93a1a1)),
  'keyword': TextStyle(color: Color(0xff859900)),
  'selector-tag': TextStyle(color: Color(0xff859900)),
  'addition': TextStyle(color: Color(0xff859900)),
  'number': TextStyle(color: Color(0xff2aa198)),
  'string': TextStyle(color: Color(0xff2aa198)),
  'literal': TextStyle(color: Color(0xff2aa198)),
  'doctag': TextStyle(color: Color(0xff2aa198)),
  'regexp': TextStyle(color: Color(0xff2aa198)),
  'title': TextStyle(color: Color(0xff268bd2)),
  'section': TextStyle(color: Color(0xff268bd2)),
  'name': TextStyle(color: Color(0xff268bd2)),
  'selector-id': TextStyle(color: Color(0xff268bd2)),
  'selector-class': TextStyle(color: Color(0xff268bd2)),
  'attribute': TextStyle(color: Color(0xffb58900)),
  'attr': TextStyle(color: Color(0xffb58900)),
  'variable': TextStyle(color: Color(0xffb58900)),
  'template-variable': TextStyle(color: Color(0xffb58900)),
  'type': TextStyle(color: Color(0xffb58900)),
  'symbol': TextStyle(color: Color(0xffcb4b16)),
  'bullet': TextStyle(color: Color(0xffcb4b16)),
  'subst': TextStyle(color: Color(0xffcb4b16)),
  'meta': TextStyle(color: Color(0xffcb4b16)),
  'selector-attr': TextStyle(color: Color(0xffcb4b16)),
  'selector-pseudo': TextStyle(color: Color(0xffcb4b16)),
  'link': TextStyle(color: Color(0xffcb4b16)),
  'built_in': TextStyle(color: Color(0xffdc322f)),
  'deletion': TextStyle(color: Color(0xffdc322f)),
  'formula': TextStyle(backgroundColor: Color(0xffeee8d5)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
