// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const hybridTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff1d1f21), color: Color(0xffc5c8c6)),
  '.hljs::selection': TextStyle(backgroundColor: Color(0xff373b41)),
  '.hljs::-moz-selection': TextStyle(backgroundColor: Color(0xff373b41)),
  'title': TextStyle(color: Color(0xfff0c674)),
  'name': TextStyle(color: Color(0xfff0c674)),
  'comment': TextStyle(color: Color(0xff707880)),
  'meta': TextStyle(color: Color(0xff707880)),
  'number': TextStyle(color: Color(0xffcc6666)),
  'symbol': TextStyle(color: Color(0xffcc6666)),
  'literal': TextStyle(color: Color(0xffcc6666)),
  'deletion': TextStyle(color: Color(0xffcc6666)),
  'link': TextStyle(color: Color(0xffcc6666)),
  'string': TextStyle(color: Color(0xffb5bd68)),
  'doctag': TextStyle(color: Color(0xffb5bd68)),
  'addition': TextStyle(color: Color(0xffb5bd68)),
  'regexp': TextStyle(color: Color(0xffb5bd68)),
  'selector-attr': TextStyle(color: Color(0xffb5bd68)),
  'selector-pseudo': TextStyle(color: Color(0xffb5bd68)),
  'attribute': TextStyle(color: Color(0xffb294bb)),
  'code': TextStyle(color: Color(0xffb294bb)),
  'selector-id': TextStyle(color: Color(0xffb294bb)),
  'keyword': TextStyle(color: Color(0xff81a2be)),
  'selector-tag': TextStyle(color: Color(0xff81a2be)),
  'bullet': TextStyle(color: Color(0xff81a2be)),
  'tag': TextStyle(color: Color(0xff81a2be)),
  'subst': TextStyle(color: Color(0xff8abeb7)),
  'variable': TextStyle(color: Color(0xff8abeb7)),
  'template-tag': TextStyle(color: Color(0xff8abeb7)),
  'template-variable': TextStyle(color: Color(0xff8abeb7)),
  'type': TextStyle(color: Color(0xffde935f)),
  'built_in': TextStyle(color: Color(0xffde935f)),
  'builtin-name': TextStyle(color: Color(0xffde935f)),
  'quote': TextStyle(color: Color(0xffde935f)),
  'section': TextStyle(color: Color(0xffde935f)),
  'selector-class': TextStyle(color: Color(0xffde935f)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
