// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const qtcreatorDarkTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff000000), color: Color(0xffaaaaaa)),
  'subst': TextStyle(color: Color(0xffaaaaaa)),
  'tag': TextStyle(color: Color(0xffaaaaaa)),
  'title': TextStyle(color: Color(0xffaaaaaa)),
  'strong': TextStyle(color: Color(0xffa8a8a2)),
  'emphasis': TextStyle(color: Color(0xffa8a8a2), fontStyle: FontStyle.italic),
  'bullet': TextStyle(color: Color(0xffff55ff)),
  'quote': TextStyle(color: Color(0xffff55ff)),
  'number': TextStyle(color: Color(0xffff55ff)),
  'regexp': TextStyle(color: Color(0xffff55ff)),
  'literal': TextStyle(color: Color(0xffff55ff)),
  'stronge': TextStyle(fontStyle: FontStyle.italic),
  'type': TextStyle(fontStyle: FontStyle.italic, color: Color(0xffff55ff)),
  'keyword': TextStyle(color: Color(0xffffff55)),
  'selector-tag': TextStyle(color: Color(0xffffff55)),
  'function': TextStyle(color: Color(0xffffff55)),
  'section': TextStyle(color: Color(0xffffff55)),
  'symbol': TextStyle(color: Color(0xffffff55)),
  'name': TextStyle(color: Color(0xffffff55)),
  'attribute': TextStyle(color: Color(0xffff5555)),
  'variable': TextStyle(color: Color(0xff8888ff)),
  'params': TextStyle(color: Color(0xff8888ff)),
  'string': TextStyle(color: Color(0xffff55ff)),
  'selector-id': TextStyle(color: Color(0xffff55ff)),
  'selector-attr': TextStyle(color: Color(0xffff55ff)),
  'selector-pseudo': TextStyle(color: Color(0xffff55ff)),
  'built_in': TextStyle(color: Color(0xffff55ff)),
  'builtin-name': TextStyle(color: Color(0xffff55ff)),
  'template-tag': TextStyle(color: Color(0xffff55ff)),
  'template-variable': TextStyle(color: Color(0xffff55ff)),
  'addition': TextStyle(color: Color(0xffff55ff)),
  'link': TextStyle(color: Color(0xffff55ff)),
  'comment': TextStyle(color: Color(0xff55ffff)),
  'meta': TextStyle(color: Color(0xff55ffff)),
  'deletion': TextStyle(color: Color(0xff55ffff)),
};
