import 'package:flutter/painting.dart';

var style = {
  'container': TextStyle(backgroundColor: Color(0xff282a36)),
  'keyword': TextStyle(color: Color(0xff8be9fd)),
  'selector-tag': TextStyle(color: Color(0xff8be9fd)),
  'literal': TextStyle(color: Color(0xff8be9fd)),
  'section': TextStyle(color: Color(0xff8be9fd)),
  'link': TextStyle(color: Color(0xff8be9fd)),
  'keyword': TextStyle(color: Color(0xffff79c6)),
  'container': TextStyle(color: Color(0xfff8f8f2)),
  'subst': TextStyle(color: Color(0xfff8f8f2)),
  'string': TextStyle(color: Color(0xfff1fa8c)),
  'title': TextStyle(color: Color(0xfff1fa8c)),
  'name': TextStyle(color: Color(0xfff1fa8c)),
  'type': TextStyle(color: Color(0xfff1fa8c)),
  'attribute': TextStyle(color: Color(0xfff1fa8c)),
  'symbol': TextStyle(color: Color(0xfff1fa8c)),
  'bullet': TextStyle(color: Color(0xfff1fa8c)),
  'addition': TextStyle(color: Color(0xfff1fa8c)),
  'variable': TextStyle(color: Color(0xfff1fa8c)),
  'template-tag': TextStyle(color: Color(0xfff1fa8c)),
  'template-variable': TextStyle(color: Color(0xfff1fa8c)),
  'comment': TextStyle(color: Color(0xff6272a4)),
  'quote': TextStyle(color: Color(0xff6272a4)),
  'deletion': TextStyle(color: Color(0xff6272a4)),
  'meta': TextStyle(color: Color(0xff6272a4)),
  'keyword': TextStyle(fontWeight: FontWeight.bold),
  'selector-tag': TextStyle(fontWeight: FontWeight.bold),
  'literal': TextStyle(fontWeight: FontWeight.bold),
  'title': TextStyle(fontWeight: FontWeight.bold),
  'section': TextStyle(fontWeight: FontWeight.bold),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'type': TextStyle(fontWeight: FontWeight.bold),
  'name': TextStyle(fontWeight: FontWeight.bold),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
};
