import 'package:flutter/painting.dart';

var style = {
  'container': TextStyle(backgroundColor: Color(0xfff4f4f4)),
  'string': TextStyle(color: Color(0xff005500)),
  'title': TextStyle(color: Color(0xff005500), fontWeight: FontWeight.bold),
  'symbol': TextStyle(color: Color(0xff005500)),
  'bullet': TextStyle(color: Color(0xff005500)),
  'attribute': TextStyle(color: Color(0xff005500)),
  'addition': TextStyle(color: Color(0xff005500)),
  'variable': TextStyle(color: Color(0xff005500)),
  'template-tag': TextStyle(color: Color(0xff005500)),
  'template-variable': TextStyle(color: Color(0xff005500)),
  'comment': TextStyle(color: Color(0xff777777)),
  'quote': TextStyle(color: Color(0xff777777)),
  'number': TextStyle(color: Color(0xff880000)),
  'regexp': TextStyle(color: Color(0xff880000)),
  'literal': TextStyle(color: Color(0xff880000)),
  'type': TextStyle(color: Color(0xff880000)),
  'link': TextStyle(color: Color(0xff880000)),
  'deletion': TextStyle(color: Color(0xff0000ee)),
  'meta': TextStyle(color: Color(0xff0000ee)),
  'keyword': TextStyle(fontWeight: FontWeight.bold),
  'selector-tag': TextStyle(fontWeight: FontWeight.bold),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'section': TextStyle(fontWeight: FontWeight.bold),
  'built_in': TextStyle(fontWeight: FontWeight.bold),
  'tag': TextStyle(fontWeight: FontWeight.bold),
  'name': TextStyle(fontWeight: FontWeight.bold),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
