import 'package:flutter/painting.dart';

var style = {
  'container':
      TextStyle(backgroundColor: Color(0xff272822), color: Color(0xffdddddd)),
  'tag': TextStyle(color: Color(0xfff92672)),
  'keyword': TextStyle(color: Color(0xfff92672)),
  'selector-tag': TextStyle(color: Color(0xfff92672)),
  'literal': TextStyle(color: Color(0xfff92672)),
  'strong': TextStyle(color: Color(0xfff92672)),
  'name': TextStyle(color: Color(0xfff92672)),
  'code': TextStyle(color: Color(0xff66d9ef)),
  'attribute': TextStyle(color: Color(0xffbf79db)),
  'symbol': TextStyle(color: Color(0xffbf79db)),
  'regexp': TextStyle(color: Color(0xffbf79db)),
  'link': TextStyle(color: Color(0xffbf79db)),
  'string': TextStyle(color: Color(0xffa6e22e)),
  'bullet': TextStyle(color: Color(0xffa6e22e)),
  'subst': TextStyle(color: Color(0xffa6e22e)),
  'title': TextStyle(color: Color(0xffa6e22e)),
  'section': TextStyle(color: Color(0xffa6e22e)),
  'emphasis': TextStyle(color: Color(0xffa6e22e)),
  'type': TextStyle(color: Color(0xffa6e22e)),
  'built_in': TextStyle(color: Color(0xffa6e22e)),
  'builtin-name': TextStyle(color: Color(0xffa6e22e)),
  'selector-attr': TextStyle(color: Color(0xffa6e22e)),
  'selector-pseudo': TextStyle(color: Color(0xffa6e22e)),
  'addition': TextStyle(color: Color(0xffa6e22e)),
  'variable': TextStyle(color: Color(0xffa6e22e)),
  'template-tag': TextStyle(color: Color(0xffa6e22e)),
  'template-variable': TextStyle(color: Color(0xffa6e22e)),
  'comment': TextStyle(color: Color(0xff75715e)),
  'quote': TextStyle(color: Color(0xff75715e)),
  'deletion': TextStyle(color: Color(0xff75715e)),
  'meta': TextStyle(color: Color(0xff75715e)),
  'keyword': TextStyle(fontWeight: FontWeight.bold),
  'selector-tag': TextStyle(fontWeight: FontWeight.bold),
  'literal': TextStyle(fontWeight: FontWeight.bold),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'title': TextStyle(fontWeight: FontWeight.bold),
  'section': TextStyle(fontWeight: FontWeight.bold),
  'type': TextStyle(fontWeight: FontWeight.bold),
  'selector-id': TextStyle(fontWeight: FontWeight.bold),
};
