import 'package:flutter/painting.dart';

var style = {
  'container': TextStyle(backgroundColor: Color(0xff2E3440)),
  'container': TextStyle(color: Color(0xffD8DEE9)),
  'subst': TextStyle(color: Color(0xffD8DEE9)),
  'selector-tag': TextStyle(color: Color(0xff81A1C1)),
  'selector-id':
      TextStyle(color: Color(0xff8FBCBB), fontWeight: FontWeight.bold),
  'selector-class': TextStyle(color: Color(0xff8FBCBB)),
  'selector-attr': TextStyle(color: Color(0xff8FBCBB)),
  'selector-pseudo': TextStyle(color: Color(0xff88C0D0)),
  'addition': TextStyle(backgroundColor: Color.fromRGBO(163, 190, 140, 0.5)),
  'deletion': TextStyle(backgroundColor: Color.fromRGBO(191, 97, 106, 0.5)),
  'built_in': TextStyle(color: Color(0xff8FBCBB)),
  'type': TextStyle(color: Color(0xff8FBCBB)),
  'class': TextStyle(color: Color(0xff8FBCBB)),
  'function': TextStyle(color: Color(0xff88C0D0)),
  'title': TextStyle(color: Color(0xff88C0D0)),
  'keyword': TextStyle(color: Color(0xff81A1C1)),
  'literal': TextStyle(color: Color(0xff81A1C1)),
  'symbol': TextStyle(color: Color(0xff81A1C1)),
  'number': TextStyle(color: Color(0xffB48EAD)),
  'regexp': TextStyle(color: Color(0xffEBCB8B)),
  'string': TextStyle(color: Color(0xffA3BE8C)),
  'title': TextStyle(color: Color(0xff8FBCBB)),
  'params': TextStyle(color: Color(0xffD8DEE9)),
  'bullet': TextStyle(color: Color(0xff81A1C1)),
  'code': TextStyle(color: Color(0xff8FBCBB)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'formula': TextStyle(color: Color(0xff8FBCBB)),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'quote': TextStyle(color: Color(0xff4C566A)),
  'comment': TextStyle(color: Color(0xff4C566A)),
  'doctag': TextStyle(color: Color(0xff8FBCBB)),
  'meta': TextStyle(color: Color(0xff5E81AC)),
  'meta-keyword': TextStyle(color: Color(0xff5E81AC)),
  'meta-string': TextStyle(color: Color(0xffA3BE8C)),
  'attr': TextStyle(color: Color(0xff8FBCBB)),
  'attribute': TextStyle(color: Color(0xffD8DEE9)),
  'builtin-name': TextStyle(color: Color(0xff81A1C1)),
  'name': TextStyle(color: Color(0xff81A1C1)),
  'section': TextStyle(color: Color(0xff88C0D0)),
  'tag': TextStyle(color: Color(0xff81A1C1)),
  'variable': TextStyle(color: Color(0xffD8DEE9)),
  'template-variable': TextStyle(color: Color(0xffD8DEE9)),
  'template-tag': TextStyle(color: Color(0xff5E81AC)),
  'attribute': TextStyle(color: Color(0xff88C0D0)),
  'symbol': TextStyle(color: Color(0xffEBCB8B)),
  'attribute': TextStyle(color: Color(0xff88C0D0)),
  'section': TextStyle(color: Color(0xff81A1C1)),
  'built_in': TextStyle(color: Color(0xff88C0D0)),
  'meta': TextStyle(color: Color(0xffD08770)),
  'title': TextStyle(color: Color(0xff88C0D0)),
  'attribute': TextStyle(color: Color(0xff8FBCBB)),
  'name': TextStyle(color: Color(0xff88C0D0)),
  'symbol': TextStyle(color: Color(0xffEBCB8B)),
  'built_in': TextStyle(color: Color(0xff88C0D0)),
  'meta-string': TextStyle(color: Color(0xff8FBCBB)),
  'built_in': TextStyle(color: Color(0xff88C0D0)),
  'keyword': TextStyle(color: Color(0xffD08770)),
  'meta': TextStyle(color: Color(0xff8FBCBB)),
  'attribute': TextStyle(color: Color(0xff8FBCBB)),
  'built_in': TextStyle(color: Color(0xff88C0D0)),
  'meta:not(:first-child)': TextStyle(color: Color(0xffD08770)),
  'meta': TextStyle(color: Color(0xffD08770)),
  'meta': TextStyle(color: Color(0xffD08770)),
  'attribute': TextStyle(color: Color(0xff8FBCBB)),
  'name': TextStyle(color: Color(0xff88C0D0)),
  'built_in': TextStyle(color: Color(0xff88C0D0)),
  'built_in': TextStyle(color: Color(0xff88C0D0)),
  'attribute': TextStyle(color: Color(0xff88C0D0)),
  'section': TextStyle(color: Color(0xff5E81AC)),
  'built_in': TextStyle(color: Color(0xff88C0D0)),
  'built_in': TextStyle(color: Color(0xff88C0D0)),
  'keyword': TextStyle(color: Color(0xff81A1C1)),
  'keyword': TextStyle(color: Color(0xff81A1C1)),
  'meta': TextStyle(color: Color(0xffD08770)),
  'built_in': TextStyle(color: Color(0xff88C0D0), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffD08770)),
};
