import 'package:flutter/painting.dart';

var style = {
  'container': TextStyle(
      backgroundColor: Color(0xff2d2b57), fontWeight: FontWeight.normal),
  'title': TextStyle(color: Color(0xfffad000), fontWeight: FontWeight.normal),
  'name': TextStyle(color: Color(0xffa1feff)),
  'tag': TextStyle(color: Color(0xffffffff)),
  'attr': TextStyle(color: Color(0xfff8d000), fontStyle: FontStyle.italic),
  'built_in': TextStyle(color: Color(0xfffb9e00)),
  'selector-tag': TextStyle(color: Color(0xfffb9e00)),
  'section': TextStyle(color: Color(0xfffb9e00)),
  'keyword': TextStyle(color: Color(0xfffb9e00)),
  'container': TextStyle(color: Color(0xffe3dfff)),
  'subst': TextStyle(color: Color(0xffe3dfff)),
  'string': TextStyle(color: Color(0xff4cd213)),
  'attribute': TextStyle(color: Color(0xff4cd213)),
  'symbol': TextStyle(color: Color(0xff4cd213)),
  'bullet': TextStyle(color: Color(0xff4cd213)),
  'addition': TextStyle(color: Color(0xff4cd213)),
  'code': TextStyle(color: Color(0xff4cd213)),
  'regexp': TextStyle(color: Color(0xff4cd213)),
  'selector-class': TextStyle(color: Color(0xff4cd213)),
  'selector-attr': TextStyle(color: Color(0xff4cd213)),
  'selector-pseudo': TextStyle(color: Color(0xff4cd213)),
  'template-tag': TextStyle(color: Color(0xff4cd213)),
  'quote': TextStyle(color: Color(0xff4cd213)),
  'deletion': TextStyle(color: Color(0xff4cd213)),
  'meta': TextStyle(color: Color(0xfffb9e00)),
  'meta-string': TextStyle(color: Color(0xfffb9e00)),
  'comment': TextStyle(color: Color(0xffac65ff)),
  'keyword': TextStyle(fontWeight: FontWeight.normal),
  'selector-tag': TextStyle(fontWeight: FontWeight.normal),
  'literal': TextStyle(fontWeight: FontWeight.normal),
  'name': TextStyle(fontWeight: FontWeight.normal),
  'strong': TextStyle(fontWeight: FontWeight.normal),
  'literal': TextStyle(color: Color(0xfffa658d)),
  'number': TextStyle(color: Color(0xfffa658d)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
