// GENERATED CODE - DO NOT MODIFY BY HAND

import 'styles/a11y-dark.dart';
import 'styles/a11y-light.dart';
import 'styles/agate.dart';
import 'styles/an-old-hope.dart';
import 'styles/androidstudio.dart';
import 'styles/arduino-light.dart';
import 'styles/arta.dart';
import 'styles/ascetic.dart';
import 'styles/atelier-cave-dark.dart';
import 'styles/atelier-cave-light.dart';
import 'styles/atelier-dune-dark.dart';
import 'styles/atelier-dune-light.dart';
import 'styles/atelier-estuary-dark.dart';
import 'styles/atelier-estuary-light.dart';
import 'styles/atelier-forest-dark.dart';
import 'styles/atelier-forest-light.dart';
import 'styles/atelier-heath-dark.dart';
import 'styles/atelier-heath-light.dart';
import 'styles/atelier-lakeside-dark.dart';
import 'styles/atelier-lakeside-light.dart';
import 'styles/atelier-plateau-dark.dart';
import 'styles/atelier-plateau-light.dart';
import 'styles/atelier-savanna-dark.dart';
import 'styles/atelier-savanna-light.dart';
import 'styles/atelier-seaside-dark.dart';
import 'styles/atelier-seaside-light.dart';
import 'styles/atelier-sulphurpool-dark.dart';
import 'styles/atelier-sulphurpool-light.dart';
import 'styles/atom-one-dark-reasonable.dart';
import 'styles/atom-one-dark.dart';
import 'styles/atom-one-light.dart';
import 'styles/brown-paper.dart';
import 'styles/codepen-embed.dart';
import 'styles/color-brewer.dart';
import 'styles/darcula.dart';
import 'styles/dark.dart';
import 'styles/darkula.dart';
import 'styles/default.dart';
import 'styles/docco.dart';
import 'styles/dracula.dart';
import 'styles/far.dart';
import 'styles/foundation.dart';
import 'styles/github-gist.dart';
import 'styles/github.dart';
import 'styles/gml.dart';
import 'styles/googlecode.dart';
import 'styles/grayscale.dart';
import 'styles/gruvbox-dark.dart';
import 'styles/gruvbox-light.dart';
import 'styles/hopscotch.dart';
import 'styles/hybrid.dart';
import 'styles/idea.dart';
import 'styles/ir-black.dart';
import 'styles/isbl-editor-dark.dart';
import 'styles/isbl-editor-light.dart';
import 'styles/kimbie.dark.dart';
import 'styles/kimbie.light.dart';
import 'styles/lightfair.dart';
import 'styles/magula.dart';
import 'styles/mono-blue.dart';
import 'styles/monokai-sublime.dart';
import 'styles/monokai.dart';
import 'styles/nord.dart';
import 'styles/obsidian.dart';
import 'styles/ocean.dart';
import 'styles/paraiso-dark.dart';
import 'styles/paraiso-light.dart';
import 'styles/pojoaque.dart';
import 'styles/purebasic.dart';
import 'styles/qtcreator_dark.dart';
import 'styles/qtcreator_light.dart';
import 'styles/railscasts.dart';
import 'styles/rainbow.dart';
import 'styles/routeros.dart';
import 'styles/school-book.dart';
import 'styles/shades-of-purple.dart';
import 'styles/solarized-dark.dart';
import 'styles/solarized-light.dart';
import 'styles/sunburst.dart';
import 'styles/tomorrow-night-blue.dart';
import 'styles/tomorrow-night-bright.dart';
import 'styles/tomorrow-night-eighties.dart';
import 'styles/tomorrow-night.dart';
import 'styles/tomorrow.dart';
import 'styles/vs.dart';
import 'styles/vs2015.dart';
import 'styles/xcode.dart';
import 'styles/xt256.dart';
import 'styles/zenburn.dart';

const themeMap = {
  'a11y-dark': a11yDarkTheme,
  'a11y-light': a11yLightTheme,
  'agate': agateTheme,
  'an-old-hope': anOldHopeTheme,
  'androidstudio': androidstudioTheme,
  'arduino-light': arduinoLightTheme,
  'arta': artaTheme,
  'ascetic': asceticTheme,
  'atelier-cave-dark': atelierCaveDarkTheme,
  'atelier-cave-light': atelierCaveLightTheme,
  'atelier-dune-dark': atelierDuneDarkTheme,
  'atelier-dune-light': atelierDuneLightTheme,
  'atelier-estuary-dark': atelierEstuaryDarkTheme,
  'atelier-estuary-light': atelierEstuaryLightTheme,
  'atelier-forest-dark': atelierForestDarkTheme,
  'atelier-forest-light': atelierForestLightTheme,
  'atelier-heath-dark': atelierHeathDarkTheme,
  'atelier-heath-light': atelierHeathLightTheme,
  'atelier-lakeside-dark': atelierLakesideDarkTheme,
  'atelier-lakeside-light': atelierLakesideLightTheme,
  'atelier-plateau-dark': atelierPlateauDarkTheme,
  'atelier-plateau-light': atelierPlateauLightTheme,
  'atelier-savanna-dark': atelierSavannaDarkTheme,
  'atelier-savanna-light': atelierSavannaLightTheme,
  'atelier-seaside-dark': atelierSeasideDarkTheme,
  'atelier-seaside-light': atelierSeasideLightTheme,
  'atelier-sulphurpool-dark': atelierSulphurpoolDarkTheme,
  'atelier-sulphurpool-light': atelierSulphurpoolLightTheme,
  'atom-one-dark-reasonable': atomOneDarkReasonableTheme,
  'atom-one-dark': atomOneDarkTheme,
  'atom-one-light': atomOneLightTheme,
  'brown-paper': brownPaperTheme,
  'codepen-embed': codepenEmbedTheme,
  'color-brewer': colorBrewerTheme,
  'darcula': darculaTheme,
  'dark': darkTheme,
  'darkula': darkulaTheme,
  'default': defaultTheme,
  'docco': doccoTheme,
  'dracula': draculaTheme,
  'far': farTheme,
  'foundation': foundationTheme,
  'github-gist': githubGistTheme,
  'github': githubTheme,
  'gml': gmlTheme,
  'googlecode': googlecodeTheme,
  'grayscale': grayscaleTheme,
  'gruvbox-dark': gruvboxDarkTheme,
  'gruvbox-light': gruvboxLightTheme,
  'hopscotch': hopscotchTheme,
  'hybrid': hybridTheme,
  'idea': ideaTheme,
  'ir-black': irBlackTheme,
  'isbl-editor-dark': isblEditorDarkTheme,
  'isbl-editor-light': isblEditorLightTheme,
  'kimbie.dark': kimbieDarkTheme,
  'kimbie.light': kimbieLightTheme,
  'lightfair': lightfairTheme,
  'magula': magulaTheme,
  'mono-blue': monoBlueTheme,
  'monokai-sublime': monokaiSublimeTheme,
  'monokai': monokaiTheme,
  'nord': nordTheme,
  'obsidian': obsidianTheme,
  'ocean': oceanTheme,
  'paraiso-dark': paraisoDarkTheme,
  'paraiso-light': paraisoLightTheme,
  'pojoaque': pojoaqueTheme,
  'purebasic': purebasicTheme,
  'qtcreator_dark': qtcreatorDarkTheme,
  'qtcreator_light': qtcreatorLightTheme,
  'railscasts': railscastsTheme,
  'rainbow': rainbowTheme,
  'routeros': routerosTheme,
  'school-book': schoolBookTheme,
  'shades-of-purple': shadesOfPurpleTheme,
  'solarized-dark': solarizedDarkTheme,
  'solarized-light': solarizedLightTheme,
  'sunburst': sunburstTheme,
  'tomorrow-night-blue': tomorrowNightBlueTheme,
  'tomorrow-night-bright': tomorrowNightBrightTheme,
  'tomorrow-night-eighties': tomorrowNightEightiesTheme,
  'tomorrow-night': tomorrowNightTheme,
  'tomorrow': tomorrowTheme,
  'vs': vsTheme,
  'vs2015': vs2015Theme,
  'xcode': xcodeTheme,
  'xt256': xt256Theme,
  'zenburn': zenburnTheme,
};
